<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FinancialFreedom.Business</RootNamespace>
    <AssemblyName>FinancialFreedom.Business</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\FinancialFreedom.Shared.csproj" />
  </ItemGroup>
</Project>
